package templates

import "text/template"

var CrudDBTemplate = template.Must(template.New("crud").Parse(`
//This file was generated by robots at {{ .Timestamp }}
//Feel free to be a part of this project: github.com/hyperxpizza/crud-generator
package database

func Get{{ .Model }}(
`))
