package templates

import "text/template"

var DockerComposeTemplate = template.Must(template.New("docker-compose").Parse(`
# This file was generated by robots at {{ .Timestamp }}
# Feel free to be a part of this project: github.com/hyperxpizza/crud-generator
version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
	postgres_data:
`))
