package templates

import "text/template"

var DockerfileTemplate = template.Must(template.New("dockerfile").Parse(`
# This file was generated by robots at {{ .Timestamp }}
# Feel free to be a part of this project: github.com/hyperxpizza/
FROM golang:1.15-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o server .

EXPOSE 8888

CMD ["./server"]
`))
