package templates

import "text/template"

var HandlersTemplate = template.Must(template.New("handlers").Parse(`
// This file was generated by robots at {{ .Timestamp }}
// Feel free to be a part of this project: github.com/hyperxpizza/crud-generator

package handlers


`))
