package templates

import "text/template"

var ModelsTemplate = template.Must(template.New("models").Parse(`
// This file was generated by robots at {{ .Timestamp }}
// Feel free to be a part of this project: github.com/hyperxpizza/crud-generator

package models
{{range .Models}}

type {{ .Model }} struct {
	{{range .Model}}
		{{ .Name }} {{ .Type }} 
	{{end}}
}

{{ end}}
`))
